site_name: VIC-WUR
site_description: Variable Infiltration Capacity Model
site_author: Wageningen University | Water System and Global Change Group (WSG)
repo_url: https://github.com/wur-wsg/VIC
site_url: http://vicwur.readthedocs.org/
theme: readthedocs
theme_dir: 'docs/custom_rtd_theme'
site_favicon: vic_favicon.jpg
copyright: GPLv2
docs_dir: docs
site_dir: site
use_directory_urls: true

pages:
# Main pages
- Home: 'index_vicwur.md'
- About:
    - 'VIC-WUR Model Overview': 'Overview/ModelOverview_vicwur.md'
    - 'VIC-WUR References': 'Documentation/References_vicwur.md'
    - 'VIC-WUR Contact': 'contact_vicwur.md'
- Documentation:
    - 'User Guide': 'Documentation/UserGuide_vicwur.md'
- Development:
    - 'Development': 'Development/ModelDevelopment_vicwur.md'
    - 'ReleaseNotes': 'Development/ReleaseNotes_vicwur.md'
- Downloads:
    - Datasets: 'Datasets/Datasets_vicwur.md'
    - Code: 'SourceCode/Code_vicwur.md'
# hidden pages
- hidden:
    # About
    - 'DamOperationText': 'Overview/DamOperationText.md'
    - 'WofostText': 'Overview/WofostText.md'
    
    # Documentation
    - 'ImageDriver': 'Documentation/Drivers/Image/ImageDriver_vicwur.md'
    - 'Inputs': 'Documentation/Drivers/Image/Inputs_vicwur.md'
    - 'GlobalParam': 'Documentation/Drivers/Image/GlobalParam_vicwur.md'
    - 'ForcingData': 'Documentation/Drivers/Image/ForcingData_vicwur.md'
    - 'RoutingParam': 'Documentation/Drivers/Image/RoutingParam.md'
    - 'IrrigationParam': 'Documentation/Drivers/Image/IrrigationParam.md'
    - 'DamParam': 'Documentation/Drivers/Image/DamParam.md'
    - 'WateruseParam': 'Documentation/Drivers/Image/WateruseParam.md'
    - 'CropParam': 'Documentation/Drivers/Image/CropParam.md'
    - 'WofostParam': 'Documentation/Drivers/Image/WofostParam.md'
    - 'RunVIC': 'Documentation/Drivers/Image/RunVIC_vicwur.md'
    - 'Constants': 'Documentation/Constants_vicwur.md'
    - 'Outputs': 'Documentation/Drivers/Image/Outputs_vicwur.md'
    - 'OutputVars': 'Documentation/OutputVarList_vicwur.md'
    - 'StateFile': 'Documentation/Drivers/Image/StateFile_vicwur.md'
    
    # Development
    - 'Testing': 'Development/Testing_vicwur.md'

markdown_extensions:
    - toc:
        permalink: True
    - admonition:
    - fenced_code:

copyright: 'GPLv2, <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt">GNU GENERAL PUBLIC LICENSE</a>.'

# google_analytics: ['UA-65965729-1', 'vicwur.readthedocs.org']
